### PR TITLE
Fixes for `@include` with Revise

### PR DESCRIPTION
**Pull request by c42f**
* Revise compatibility: it appears Revise needs string literals in
  `include()`.  So emit `include("file.jl")` rather than
  `file="file.jl"; include(file)` from `@include`.
* Fix a problem with relative paths and `isfile`: `isfile` acts relative
  to the current path `pwd()`, but `include` acts relative to the
  current parent .jl file in tls[:SOURCE_PATH].

If I understand correctly what's going on here, this should fix https://github.com/JuliaPackaging/Requires.jl/issues/94 @timholy

### CODE REVIEW

**Review by timholy — APPROVED** [review]

**Comment by timholy** [comment]
Thanks so much for doing this! I'll let you decide when to merge this, but it sure smells like v1.1.1 to me. I'll remove the bound-restriction in Revise as soon as that's out.

**Comment by c42f** [comment]
Well I figured I should take a crack at this, given that I was responsible for pushing #85 through.

I don't have write access to this repo btw so I can't merge it. (But I admit I'm kinda ok with that situation :laughing:)

A new point release with this bugfix would make sense.

@andreasnoack it would be nice to double check that this does this work with your use case if it's not too much trouble. You've got a bit of an unusual setup with Pumas and I'm not sure whether it's really captured in the tests.

**Comment by andreasnoack** [comment]
We'll test this next week and report back if the system image generation still works.

**Comment by andreasnoack** [comment]
We've now tested this and systems images are still relocatable with this PR so it should good to merge.

**Pull request merged**
